export namespace RendManageType {
  export class getrendState {
    id?: string | undefined;
    area?: string | undefined;
    name?: string | undefined;
    pageCount?: number | undefined;
    pageSize?: number | undefined;
    brand?: string | undefined;
    broker?: string | undefined;
    building_type?: string | undefined;
    create_time?: string | undefined;
    extent?: string | undefined;
    feature?: string | undefined;
    house_type?: string | undefined;
    img?: string | undefined;
    lease?: string | undefined;
    lift?: string | undefined;
    ll?: string | undefined;
    pay?: string | undefined;
    periods?: string | undefined;
    position?: string | undefined;
    price?: string | undefined;
    renovation?: string | undefined;
    resident?: string | undefined;
    section?: string | undefined;
    status?: string | undefined;
    subway?: string | undefined;
    toward?: string | undefined;
    update_time?: string | undefined;
    useto?: string | undefined;
    way?: string | undefined;
  }
  export class renddataState {
    id?: string | undefined;
    area?: string | undefined;
    name?: string | undefined;
    pageCount?: number | undefined;
    pageSize?: number | undefined;
    brand?: string | undefined;
    broker?: string | undefined;
    building_type?: string | undefined;
    create_time?: string | undefined;
    extent?: number | undefined | any;
    feature?: string | undefined;
    house_type?: string | undefined;
    img?: string | undefined;
    lease?: string | undefined;
    lift?: string | undefined;
    ll?: string | undefined;
    pay?: string | undefined;
    periods?: string | undefined;
    position?: string | undefined;
    price?: string | undefined;
    renovation?: string | undefined;
    resident?: string | undefined;
    section?: string | undefined;
    status?: string | undefined;
    subway?: string | undefined;
    toward?: string | undefined;
    update_time?: string | undefined;
    useto?: string | undefined;
    way?: string | undefined;
  }
}
